// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ayalas_street_dogs.Models;

#nullable disable

namespace ayalas_street_dogs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410071438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ayalas_street_dogs.Models.AjusteInventario", b =>
                {
                    b.Property<int>("IdAjuste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAjuste"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("Cantidad");

                    b.Property<DateTime>("FechaAjuste")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdIngrediente")
                        .HasColumnType("int(11)");

                    b.Property<string>("Motivo")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdAjuste")
                        .HasName("PRIMARY");

                    b.HasIndex("IdIngrediente");

                    b.ToTable("ajusteinventario", (string)null);
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.CategoriaMenu", b =>
                {
                    b.Property<int>("IdCategoriaMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCategoriaMenu");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategoriaMenu"));

                    b.Property<string>("Icono")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("basket")
                        .HasColumnName("icono");

                    b.Property<string>("NombreCategoriaMenu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreCategoriaMenu");

                    b.Property<int>("OrdenVisualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ordenVisualizacion");

                    b.HasKey("IdCategoriaMenu");

                    b.ToTable("categoriaMenu", (string)null);
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Categorium", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idCategoria");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreCategoria");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("enum('Producto','Servicio')")
                        .HasColumnName("tipo");

                    b.HasKey("IdCategoria")
                        .HasName("PRIMARY");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idCompra");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<DateTime?>("FechaC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaC")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<decimal>("TotalC")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("totalC");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("usuario");

                    b.HasKey("IdCompra")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Usuario" }, "FK_Compra_Usuario");

                    b.ToTable("compra", (string)null);
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.DetallePlatillo", b =>
                {
                    b.Property<int>("IdDetallePlatillo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDetallePlatillo"));

                    b.Property<decimal>("CantidadConsumida")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("CantidadConsumida");

                    b.Property<int>("IdIngrediente")
                        .HasColumnType("int(11)");

                    b.Property<int>("IdPlatillo")
                        .HasColumnType("int(11)");

                    b.HasKey("IdDetallePlatillo")
                        .HasName("PRIMARY");

                    b.HasIndex("IdIngrediente");

                    b.HasIndex("IdPlatillo");

                    b.ToTable("detalleplatillo", (string)null);
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Detallecompra", b =>
                {
                    b.Property<int>("IdCompra")
                        .HasColumnType("int(11)")
                        .HasColumnName("idCompra");

                    b.Property<int>("idIngrediente")
                        .HasColumnType("int(11)")
                        .HasColumnName("idIngrediente");

                    b.Property<int>("CantidadDc")
                        .HasPrecision(10, 3)
                        .HasColumnType("int")
                        .HasColumnName("cantidadDC");

                    b.Property<decimal>("CostoDc")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("costoDC");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int(11)")
                        .HasColumnName("idProveedor");

                    b.HasKey("IdCompra", "idIngrediente")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "idIngrediente" }, "FK_DetalleCompra_Ingrediente");

                    b.HasIndex(new[] { "IdProveedor" }, "FK_DetalleCompra_Proveedor");

                    b.ToTable("detallecompra", (string)null);
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Detalleventum", b =>
                {
                    b.Property<int>("IdVenta")
                        .HasColumnType("int(11)")
                        .HasColumnName("idVenta");

                    b.Property<int>("IdPlatillo")
                        .HasColumnType("int(11)")
                        .HasColumnName("idPlatillo");

                    b.Property<int>("CantidadDv")
                        .HasColumnType("int(11)")
                        .HasColumnName("cantidadDV");

                    b.Property<decimal>("CostoDv")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("costoDV");

                    b.HasKey("IdVenta", "IdPlatillo")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdPlatillo" }, "FK_DetalleVenta_Platillo");

                    b.ToTable("detalleventa", (string)null);
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Ingrediente", b =>
                {
                    b.Property<int>("IdIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("IdIngrediente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdIngrediente"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<decimal>("CostoUnitarioPromedio")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("CostoUnitarioPromedio");

                    b.Property<DateTime?>("FechaDesactivacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaDesactivacion");

                    b.Property<string>("MotivoDesactivacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("MotivoDesactivacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("StockActual")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("StockActual");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("StockMinimo");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdIngrediente")
                        .HasName("PRIMARY");

                    b.ToTable("ingrediente", (string)null);
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Platillo", b =>
                {
                    b.Property<int>("IdPlatillo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idPlatillo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPlatillo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("IdCategoriaMenu")
                        .HasColumnType("int(11)")
                        .HasColumnName("idCategoriaMenu");

                    b.Property<string>("NombrePlatillo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombrePlatillo");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("IdPlatillo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCategoriaMenu" }, "FK_Platillo_CategoriaMenu");

                    b.ToTable("platillo", (string)null);
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idProveedor");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("direccion");

                    b.Property<string>("EmailProveedor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("emailProveedor");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int(11)")
                        .HasColumnName("idCategoria");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreProveedor");

                    b.Property<string>("TelefonoProveedor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefonoProveedor");

                    b.HasKey("IdProveedor")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCategoria" }, "FK_Proveedor_Categoria");

                    b.HasIndex(new[] { "EmailProveedor" }, "emailProveedor")
                        .IsUnique();

                    b.ToTable("proveedor", (string)null);
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Usuario", b =>
                {
                    b.Property<string>("Usuario1")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("usuario");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contrasena");

                    b.Property<string>("EmailUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("emailUsuario");

                    b.Property<string>("Nombres")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombres");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("enum('admin','empleado','cliente')")
                        .HasColumnName("rol");

                    b.Property<string>("TelefonoUsuario")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefonoUsuario");

                    b.HasKey("Usuario1")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmailUsuario" }, "emailUsuario")
                        .IsUnique();

                    b.HasIndex(new[] { "TelefonoUsuario" }, "telefonoUsuario")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Ventum", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idVenta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaV")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreCliente");

                    b.Property<decimal>("TotalV")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("totalV");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("usuario");

                    b.HasKey("IdVenta")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Usuario" }, "FK_Venta_Usuario");

                    b.ToTable("venta", (string)null);
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.AjusteInventario", b =>
                {
                    b.HasOne("ayalas_street_dogs.Models.Ingrediente", "IdIngredienteNavigation")
                        .WithMany("AjusteInventarios")
                        .HasForeignKey("IdIngrediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AjusteInventario_Ingrediente");

                    b.Navigation("IdIngredienteNavigation");
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Compra", b =>
                {
                    b.HasOne("ayalas_street_dogs.Models.Usuario", "UsuarioNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Compra_Usuario");

                    b.Navigation("UsuarioNavigation");
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.DetallePlatillo", b =>
                {
                    b.HasOne("ayalas_street_dogs.Models.Ingrediente", "IdIngredienteNavigation")
                        .WithMany("DetallePlatillos")
                        .HasForeignKey("IdIngrediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetallePlatillo_Ingrediente");

                    b.HasOne("ayalas_street_dogs.Models.Platillo", "IdPlatilloNavigation")
                        .WithMany("Detalleplatillo")
                        .HasForeignKey("IdPlatillo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetallePlatillo_Platillo");

                    b.Navigation("IdIngredienteNavigation");

                    b.Navigation("IdPlatilloNavigation");
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Detallecompra", b =>
                {
                    b.HasOne("ayalas_street_dogs.Models.Compra", "IdCompraNavigation")
                        .WithMany("Detallecompras")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetalleCompra_Compra");

                    b.HasOne("ayalas_street_dogs.Models.Proveedor", "IdProveedorNavigation")
                        .WithMany("Detallecompras")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleCompra_Proveedor");

                    b.HasOne("ayalas_street_dogs.Models.Ingrediente", "IdIngredienteNavigation")
                        .WithMany("Detallecompras")
                        .HasForeignKey("idIngrediente")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleCompra_Ingrediente");

                    b.Navigation("IdCompraNavigation");

                    b.Navigation("IdIngredienteNavigation");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Detalleventum", b =>
                {
                    b.HasOne("ayalas_street_dogs.Models.Platillo", "IdPlatilloNavigation")
                        .WithMany("Detalleventa")
                        .HasForeignKey("IdPlatillo")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleVenta_Platillo");

                    b.HasOne("ayalas_street_dogs.Models.Ventum", "IdVentaNavigation")
                        .WithMany("Detalleventa")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetalleVenta_Venta");

                    b.Navigation("IdPlatilloNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Platillo", b =>
                {
                    b.HasOne("ayalas_street_dogs.Models.CategoriaMenu", "IdCategoriaMenuNavigation")
                        .WithMany("Platillos")
                        .HasForeignKey("IdCategoriaMenu")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Platillo_CategoriaMenu");

                    b.Navigation("IdCategoriaMenuNavigation");
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Proveedor", b =>
                {
                    b.HasOne("ayalas_street_dogs.Models.Categorium", "IdCategoriaNavigation")
                        .WithMany("Proveedors")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Proveedor_Categoria");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Ventum", b =>
                {
                    b.HasOne("ayalas_street_dogs.Models.Usuario", "UsuarioNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Venta_Usuario");

                    b.Navigation("UsuarioNavigation");
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.CategoriaMenu", b =>
                {
                    b.Navigation("Platillos");
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Categorium", b =>
                {
                    b.Navigation("Proveedors");
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Compra", b =>
                {
                    b.Navigation("Detallecompras");
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Ingrediente", b =>
                {
                    b.Navigation("AjusteInventarios");

                    b.Navigation("DetallePlatillos");

                    b.Navigation("Detallecompras");
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Platillo", b =>
                {
                    b.Navigation("Detalleplatillo");

                    b.Navigation("Detalleventa");
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Proveedor", b =>
                {
                    b.Navigation("Detallecompras");
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Usuario", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("ayalas_street_dogs.Models.Ventum", b =>
                {
                    b.Navigation("Detalleventa");
                });
#pragma warning restore 612, 618
        }
    }
}
